In [46]:
import numpy as np
import pandas as pd
import random 
import math

Testing Numpy arrays

In [3]:
A = np.array([[1,2,3], [1,2,3],[1,2,3]])
B = np.array([[1,2,3], [1,2,3],[1,2,3]])
C = A * B
print(C)

[[1 4 9]
 [1 4 9]
 [1 4 9]]


testing scalars

In [4]:
A = np.array([[1,2,3], [1,2,3],[1,2,3]])
A = A * 2
print(A)

[[2 4 6]
 [2 4 6]
 [2 4 6]]


Testing weight style system, on alabama

In [5]:
Weight = np.array([.14, -.16]) #(Male, Female), [-.22, -.23, .04, 0.19]
Population = np.array([.49, .51]) #(Male, Female), [.13, .22, .41, .23]
print(Weight)
Outcome = sum(Weight * Population)

#print(Outcome)

[ 0.14 -0.16]


Dictonary Method

In [6]:
Weight = {} 
Weight['Age'] = [-.22, -.23, .04, 0.19]
Weight['Gender'] = [.49, .51]
Weight['Race']

Pop = {}
Pop['Age'] = [.13, .22, .41, .23]
Pop['Gender'] = [.49, .51]


Outcome = 0

for key in Weight.keys():
    
    for i in range(len(Weight[key])):
        Outcome += Pop[key][i] * Weight[key][i]
        
print(Outcome)
    

KeyError: 'Race'

numpy

In [7]:
Weight = {} 
Weight['Age'] = np.array([-.22, -.23, .04, 0.19])
Weight['Gender'] = np.array([.49, .51])

Pop = {}
Pop['Age'] = np.array([.13, .22, .41, .23])
Pop['Gender'] = np.array([.49, .51])


Outcome = 0

for key in Weight.keys():
    Outcome += sum(Pop[key] * Weight[key])
        
print(Outcome)

0.48109999999999997


trying to read in some data

In [8]:
file = open('exit_polls_data_cnn_04022017.csv', 'r')


pandas attempt

In [9]:
df = pd.read_csv('exit_polls_data_cnn_04022017.csv')
print(df)

      questions_id                                          questions  \
0                1                                             Gender   
1                1                                             Gender   
2                2                                                Age   
3                2                                                Age   
4                2                                                Age   
5                2                                                Age   
6                3                                                Age   
7                3                                                Age   
8                3                                                Age   
9                3                                                Age   
10               3                                                Age   
11               3                                                Age   
12               4                                 

In [10]:
print(df.loc[(df['questions'] == 'Gender') & (df['state'] == 'nation')])

   questions_id questions  num_respondents options  Clinton_perc  Trump_perc  \
0             1    Gender            24558    Male          41.0        52.0   
1             1    Gender            24558  Female          54.0        41.0   

   Others_Unknown_perc  options_perc   state  \
0                  7.0          47.0  nation   
1                  5.0          53.0  nation   

                                                 url  
0  http://www.cnn.com/election/results/exit-polls...  
1  http://www.cnn.com/election/results/exit-polls...  


Converting pandas to dictonary of weights

In [11]:
pop = {}
weight = {}
questions = ['Gender', 'Age', 'Race', 'Education', 'Income', 'Party ID', 'Ideology', 'Marital status', 'Religion', 'How often do you attend religious services?', 'Union household?']
for i in questions:
    pop[i] = np.array(df.loc[(df['state'] == 'nation') & (df['questions'] == i)]['options_perc']/100)
    weight[i] = np.array((df.loc[(df['state'] == 'nation') & (df['questions'] == i)]['Trump_perc']) - (df.loc[(df['state'] == 'nation') & (df['questions'] == i)]['Clinton_perc']))/100
print(pop['Age'])
print(weight['Age'])

 

for key in weight.keys():
    Outcome += sum(pop[key] * weight[key])
print(Outcome)

[0.19 0.25 0.4  0.16 0.1  0.09 0.17 0.19 0.3  0.16 0.44 0.56]
[-0.19 -0.1   0.08  0.07 -0.22 -0.16 -0.12  0.03  0.08  0.07 -0.14  0.08]
nan


In [12]:
pop_virginia = {}
for i in questions:
    pop_virginia[i] = np.array(df.loc[(df['state'] == 'Arizona') & (df['questions'] == i)]['options_perc']/100)


data cleaning function 

In [27]:
def pop_weight(df, questions=['Gender', 'Age', 'Race', 'Education', 'Income', 'Party ID', 'Ideology', 'Marital status', 'Religion', 'How often do you attend religious services?', 'Union household?']): 
    pop = {}
    df = df.fillna(0)
    Outcome = 0
    for i in questions:
        pop[i] = np.array(df.loc[(df['state'] == 'nation') & (df['questions'] == i)]['options_perc']/100)
        weight[i] = np.array((df.loc[(df['state'] == 'nation') & (df['questions'] == i)]['Trump_perc']) - (df.loc[(df['state'] == 'nation') & (df['questions'] == i)]['Clinton_perc']))/100
    
    print(sum(pop['Gender'] *  weight['Gender']))
    print(sum(weight['Age'][0:4] * pop['Age'][0:4]))
    
    for key in weight.keys():
        Outcome += sum(pop[key] * weight[key])
    print(Outcome)

    
(pop_weight(df))

-0.017200000000000007
-0.0179
-0.35560000000000014


promblem is that they all have like a 1.7% prefrence which just adds up over time. Going to try with just race

In [43]:
df = df.fillna(0)
pop_virginia = np.array(df.loc[(df['state'] == 'Virginia') & (df['questions'] == 'Religion')]['options_perc']/100)
weight = np.array((df.loc[(df['state'] == 'nation') & (df['questions'] == 'Religion')]['Trump_perc']) - (df.loc[(df['state'] == 'nation') & (df['questions'] == 'Religion')]['Clinton_perc']))/100

print(weight)


[ 0.23  0.04  0.28  0.11 -0.48  0.   -0.26 -0.42  0.17  0.04 -0.48 -0.33
 -0.42]


Idea: <br> 

Utah <br> 

<pre>
<b>Population Weights</b><br>
Race: (0.861, .02, ...) <br>
Ethnicity: (0.78, 0.22) #Hispanic <br>
Religion: (0.62, 0.12, ...) <br> 
Religious Attendence: (0.12, 0.22, 0.3, ...) <br> 
Gender: (0.56, 0.44) <br>
LGBT+: (0.96, 0.04) <br>
Education: (0.08, 0.12, 0.38, ...) <br>
Income: (0.36, 0.12, 0.42, ...) <br> 
    
    
<b>Voting Weights</b><br>
Race: (0.2, -.02, ...) <br>
Ethnicity: (0.13, -0.22) #Hispanic <br>
Religion: (0.56, -0.12, ...) <br> 
ect..
</pre>


1000 Agents per state

86.1% are white, with 62% being mormon ect...

In [ ]:
'''
class Voter: 
    
    def __init__(self):
        pass
    
    def vote(self): 
        return race + religion + religosity + gender + queer + education + income + random_walk
        
class State: 
    
    def __init__(self):
        pass
        
    def demographics(self): 
        demographics = [voter1, voter2, ...]
    
    def vote(self): 
        return         
'''       

Voter Class

In [52]:
class Voter: 
    
    def __init__(self, into, walk=0.05):
        
        self.race = into['race']
        self.religion = into['religion']
        self.religosity = into['religosity']
        self.gender = into['gender']
        self.queer = into['queer']
        self.education = into['education']
        self.income = into['income']
        self.random_walk = walk
    
    def vote(self): 
        '''
        race = (race[0] * race[1])
        religion = (religion[0] * religion[1])
        religosity = (religosity[0] * religosity[1])
        gender = (gender[0] * gender[1])
        queer = (queer[0] * queer[1])
        education = (education[0] * education[1])
        income = (income[0] * income[1]) 
        '''
        random_walk = random.randrange(walk*-1, walk, walk/5)
        
        return  np.sign(race + religion + religosity + gender + queer + education + income + random_walk)



State Class

In [54]:
class State: 
    def __init__(self, demograpics, weights):
        self.demograpics = demograpics
        self.voters = {}
        self.weights = weights
        
    def demographics(self): 
        for i in range(1000):
            
            into = {
                'race':[], 
                'religion':[], 
                'religosity':[], 
                'gender':[], 
                'queer':[], 
                'education':[], 
                'income':[],
            } 
            
            for char in self.demograpics.keys(): 
                for i in range(int(char * 1000)):
                    into[str(char)].append(self.weights[])
            for race, religion, religosity, gender, queer, education, income \
            in self.demograpics['race'], self.demograpics['religion'], self.demograpics['religosity'], \
            self.demograpics['gender'],self.demograpics['queer'], self.demograpics['education'], \
            self.demograpics['income']:
                
                self.voters[i] = 
                
    
    def vote(self): 
        return   

In [55]:
print(0.86 * 1000)

860.0
